name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:__GO_VERSION__
    steps:
      - uses: actions/checkout@v4
__GO_TEST_STEPS__
      - name: Install doctest
        run: |
          if ! command -v doctest >/dev/null 2>&1; then
            go install github.com/xhd2015/doctest/cmd/doctest@latest
          fi
      - name: Doctest
        run: doctest test -v --label-all ./...
