package api

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const apiBackendResponses = "responses"

// ModelsCache is ~/.grok/models_cache.json.
type ModelsCache struct {
	ETag        string                 `json:"etag"`
	GrokVersion string                 `json:"grok_version"`
	Models      map[string]CachedModel `json:"models"`
}

// CachedModel is one entry in ModelsCache.Models.
type CachedModel struct {
	Info ModelInfo `json:"info"`
}

// ModelInfo is the catalog fields used by the loopback proxy.
type ModelInfo struct {
	ID               string            `json:"id"`
	Model            string            `json:"model"`
	Name             string            `json:"name"`
	Description      string            `json:"description"`
	APIBackend       string            `json:"api_backend"`
	ContextWindow    uint64            `json:"context_window"`
	SupportedInAPI   bool              `json:"supported_in_api"`
	Hidden           bool              `json:"hidden"`
	ReasoningEfforts []ReasoningEffort `json:"reasoning_efforts"`
}

// ReasoningEffort is one advertised Grok reasoning level.
type ReasoningEffort struct {
	Value   string `json:"value"`
	Default bool   `json:"default"`
}

// ModelsCachePath returns home/models_cache.json.
func ModelsCachePath(home string) (string, error) {
	home = strings.TrimSpace(home)
	if home == "" {
		var err error
		home, err = DefaultHome()
		if err != nil {
			return "", err
		}
	}
	return filepath.Join(home, "models_cache.json"), nil
}

// ReadModelsCache loads a Grok models_cache.json file.
func ReadModelsCache(path string) (ModelsCache, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		return ModelsCache{}, fmt.Errorf("grok api: empty models cache path")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return ModelsCache{}, fmt.Errorf("grok api: read models cache: %w", err)
	}
	var cache ModelsCache
	if err := json.Unmarshal(data, &cache); err != nil {
		return ModelsCache{}, fmt.Errorf("grok api: decode models cache: %w", err)
	}
	return cache, nil
}

// listedModels returns visible, API-supported models sorted by id.
func listedModels(cache ModelsCache) []ModelInfo {
	ids := make([]string, 0, len(cache.Models))
	for id := range cache.Models {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	out := make([]ModelInfo, 0, len(ids))
	for _, id := range ids {
		info := cache.Models[id].Info
		if info.ID == "" {
			info.ID = id
		}
		if info.Hidden || !info.SupportedInAPI {
			continue
		}
		out = append(out, info)
	}
	return out
}

// ModelsV2Entry is one Grok CLI catalog row (GET /v1/models-v2).
type ModelsV2Entry struct {
	ID            string `json:"id"`
	Model         string `json:"model"`
	Name          string `json:"name"`
	Description   string `json:"description,omitempty"`
	ContextWindow uint64 `json:"context_window,omitempty"`
	BaseURL       string `json:"base_url"`
	APIBackend    string `json:"api_backend"`
}

// ModelsV2Response is the Grok CLI catalog payload.
type ModelsV2Response struct {
	Data []ModelsV2Entry `json:"data"`
}

// ModelsV2 builds the loopback catalog from cache.
func ModelsV2(cache ModelsCache, endpoint string) ModelsV2Response {
	models := listedModels(cache)
	resp := ModelsV2Response{Data: make([]ModelsV2Entry, 0, len(models))}
	backend := apiBackendResponses
	for _, m := range models {
		if m.APIBackend != "" {
			backend = m.APIBackend
		}
		name := m.Name
		if name == "" {
			name = m.ID
		}
		resp.Data = append(resp.Data, ModelsV2Entry{
			ID:            m.ID,
			Model:         m.ID,
			Name:          name,
			Description:   m.Description,
			ContextWindow: m.ContextWindow,
			BaseURL:       endpoint,
			APIBackend:    backend,
		})
	}
	return resp
}

// OpenAIModelsResponse is GET /v1/models.
type OpenAIModelsResponse struct {
	Object string          `json:"object"`
	Data   []OpenAIModelID `json:"data"`
}

// OpenAIModelID is one OpenAI-list model row.
type OpenAIModelID struct {
	ID     string `json:"id"`
	Object string `json:"object"`
}

// OpenAIModels lists cache ids in OpenAI shape.
func OpenAIModels(cache ModelsCache) OpenAIModelsResponse {
	models := listedModels(cache)
	resp := OpenAIModelsResponse{Object: "list", Data: make([]OpenAIModelID, 0, len(models))}
	for _, m := range models {
		resp.Data = append(resp.Data, OpenAIModelID{ID: m.ID, Object: "model"})
	}
	return resp
}

// CodexConfig prints a ~/.codex/config.toml snippet for the Grok proxy.
func CodexConfig(endpoint string, cache ModelsCache) string {
	if strings.TrimSpace(endpoint) == "" {
		endpoint = fmt.Sprintf("http://localhost:%d/v1", DefaultPort)
	}
	var out strings.Builder
	fmt.Fprintf(&out, "# Paste into ~/.codex/config.toml\n")
	fmt.Fprintf(&out, "# Generated by: llm-proxy grok-models\n")
	fmt.Fprintf(&out, "# Endpoint: %s\n", endpoint)
	models := listedModels(cache)
	defaultModel := "grok-4.6"
	if len(models) > 0 {
		defaultModel = models[0].ID
		fmt.Fprintf(&out, "# Models:\n")
		for _, m := range models {
			fmt.Fprintf(&out, "#   %s\n", m.ID)
			for _, e := range m.ReasoningEfforts {
				if e.Value == "" {
					continue
				}
				fmt.Fprintf(&out, "#   %s:%s\n", m.ID, e.Value)
			}
		}
	}
	fmt.Fprintf(&out, "\nmodel = %q\n", defaultModel)
	fmt.Fprintf(&out, "model_provider = \"llm-proxy\"\n\n")
	fmt.Fprintf(&out, "[model_providers.llm-proxy]\n")
	fmt.Fprintf(&out, "name = \"Grok Subscription\"\n")
	fmt.Fprintf(&out, "base_url = %q\n", endpoint)
	fmt.Fprintf(&out, "wire_api = \"responses\"\n")
	return out.String()
}

// DSHBaseURL turns a proxy endpoint into the DSH openai-responses baseURL.
// The OpenAI SDK posts {baseURL}/responses, so this keeps /v1.
func DSHBaseURL(endpoint string) string {
	s := strings.TrimSpace(endpoint)
	s = strings.TrimRight(s, "/")
	if s == "" {
		s = fmt.Sprintf("http://127.0.0.1:%d/v1", DefaultPort)
	}
	s = strings.Replace(s, "://localhost", "://127.0.0.1", 1)
	if !strings.HasSuffix(s, "/v1") {
		s += "/v1"
	}
	return s
}

// DSHSettingsYAML prints a ~/.dsh/settings.yaml llm-pi-ai provider block.
func DSHSettingsYAML(endpoint string, cache ModelsCache) string {
	base := DSHBaseURL(endpoint)
	models := listedModels(cache)
	if len(models) == 0 {
		models = []ModelInfo{{
			ID:            "grok-4.6",
			Name:          "Grok 4.6",
			ContextWindow: 500000,
			ReasoningEfforts: []ReasoningEffort{
				{Value: "low"},
				{Value: "medium"},
				{Value: "high", Default: true},
				{Value: "xhigh"},
			},
		}}
	}
	var out strings.Builder
	fmt.Fprintf(&out, "llm-pi-ai:\n")
	fmt.Fprintf(&out, "  providers:\n")
	fmt.Fprintf(&out, "    grok:\n")
	fmt.Fprintf(&out, "      displayName: Grok (llm-proxy)\n")
	fmt.Fprintf(&out, "      apiKeyEnv: GROK_API_KEY\n")
	fmt.Fprintf(&out, "      api: openai-responses\n")
	fmt.Fprintf(&out, "      baseURL: %s\n", base)
	fmt.Fprintf(&out, "      reasoning: high\n")
	fmt.Fprintf(&out, "      models:\n")
	for _, m := range models {
		name := m.Name
		if name == "" {
			name = m.ID
		}
		fmt.Fprintf(&out, "        - id: %s\n", m.ID)
		fmt.Fprintf(&out, "          name: %s\n", name)
		fmt.Fprintf(&out, "          input: [ text ]\n")
		if m.ContextWindow > 0 {
			fmt.Fprintf(&out, "          contextWindow: %d\n", m.ContextWindow)
		}
		efforts := m.ReasoningEfforts
		if len(efforts) == 0 {
			efforts = []ReasoningEffort{{Value: "low"}, {Value: "medium"}, {Value: "high"}, {Value: "xhigh"}}
		}
		fmt.Fprintf(&out, "          reasoningEfforts:\n")
		for _, e := range efforts {
			if e.Value == "" {
				continue
			}
			fmt.Fprintf(&out, "            %s: %s\n", e.Value, e.Value)
		}
	}
	fmt.Fprintf(&out, "\n# openai-responses posts {baseURL}/responses, so baseURL includes /v1.\n")
	fmt.Fprintf(&out, "# The proxy reads ~/.grok/auth.json and ignores the client key.\n")
	return out.String()
}
