package ptywrap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type rcPatchOptions struct {
	ExtraPaths []string
	PS1        string
}

func buildPatchLines(opts rcPatchOptions) string {
	var lines []string
	if len(opts.ExtraPaths) > 0 {
		lines = append(lines, fmt.Sprintf("export PATH=$PATH:%s", strings.Join(opts.ExtraPaths, ":")))
	}
	if opts.PS1 != "" {
		lines = append(lines, fmt.Sprintf("export PS1=%s", ShellQuote(opts.PS1)))
	}
	return strings.Join(lines, "\n")
}

func writeCustomBashRC(opts rcPatchOptions) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get home dir: %w", err)
	}

	rcPath := filepath.Join(home, ".ptywrap-bashrc")

	var sources []string
	for _, f := range []string{".bash_profile", ".bashrc", ".profile"} {
		p := filepath.Join(home, f)
		if _, err := os.Stat(p); err == nil {
			sources = append(sources, fmt.Sprintf("[ -f %s ] && . %s", ShellQuote(p), ShellQuote(p)))
		}
	}

	patchLines := buildPatchLines(opts)

	var content strings.Builder
	content.WriteString("# Auto-generated by ptywrap. Do not edit.\n")
	for _, s := range sources {
		content.WriteString(s + "\n")
	}
	if patchLines != "" {
		content.WriteString("\n# ptywrap customizations\n")
		content.WriteString(patchLines + "\n")
	}

	if err := os.WriteFile(rcPath, []byte(content.String()), 0644); err != nil {
		return "", fmt.Errorf("write %s: %w", rcPath, err)
	}
	return rcPath, nil
}

func writeCustomZshRC(opts rcPatchOptions) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get home dir: %w", err)
	}

	zdotdir := filepath.Join(home, ".ptywrap-zsh")
	if err := os.MkdirAll(zdotdir, 0755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", zdotdir, err)
	}

	rcPath := filepath.Join(zdotdir, ".zshrc")
	origZshrc := filepath.Join(home, ".zshrc")
	patchLines := buildPatchLines(opts)

	var content strings.Builder
	content.WriteString("# Auto-generated by ptywrap. Do not edit.\n")
	if _, err := os.Stat(origZshrc); err == nil {
		content.WriteString(fmt.Sprintf("[ -f %s ] && . %s\n", ShellQuote(origZshrc), ShellQuote(origZshrc)))
	}
	if patchLines != "" {
		content.WriteString("\n# ptywrap customizations\n")
		content.WriteString(patchLines + "\n")
	}

	if err := os.WriteFile(rcPath, []byte(content.String()), 0644); err != nil {
		return "", fmt.Errorf("write %s: %w", rcPath, err)
	}
	return zdotdir, nil
}

func replaceLoginWithRCFile(flags []string, rcFile string) []string {
	var result []string
	replaced := false
	for _, f := range flags {
		if f == "--login" || f == "-l" {
			result = append(result, "--rcfile", rcFile)
			replaced = true
			continue
		}
		result = append(result, f)
	}
	if !replaced {
		result = append([]string{"--rcfile", rcFile}, result...)
	}
	return result
}